# Generated by Django 2.1.7 on 2019-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_instances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='name',
            field=models.CharField(default='MxGateway', max_length=20),
        ),
        migrations.AlterField(
            model_name='credential',
            name='database',
            field=models.CharField(default='mxhero', max_length=20),
        ),
        migrations.AlterField(
            model_name='credential',
            name='host',
            field=models.CharField(default='192.168.6.80:3306', max_length=100),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(default='xxxxxx', max_length=20),
        ),
        migrations.AlterField(
            model_name='credential',
            name='user',
            field=models.CharField(default='mxgateway', max_length=20),
        ),
    ]
