# Generated by Django 2.1.7 on 2019-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_instances', '0002_auto_20190318_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
